### PR TITLE
Model Completed

### PR DESCRIPTION
**Pull request by Richiio**

### CODE REVIEW

**Comment by Richiio** [comment]
Model cleaning done

**Comment by GemmaTuron** [comment]
Hi @Richiio !

did the remove of the features not work? I think we DO want to remove them, as they will only occupy space in the user's system

**Comment by Richiio** [comment]
Yes, I didn't. It broke when I removed the mock.txt and tensorboard. Although it worked fine on my local system after I made the removal as seen here: 
```
(eos9ei3) root@Richio:~/eos5xng-main/model/framework# bash run.sh . ~/Desktop/test.csv ~/Desktop/output.csv
now getting features
100%|██████████████████████████████████████████████████████████████████████████████████████████████| 2955/2955 [01:04<00:00, 45.77it/s]finished getting features
now predicting
Loading training args
Loading data
2955it [00:00, 136326.99it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████| 2955/2955 [00:00<00:00, 40351.25it/s]Validating SMILES
Test size = 2,955
Predicting with an ensemble of 5 models
  0%|                                                                                                            | 0/5 [00:00<?, ?it/s]Loading pretrained parameter "encoder.encoder.cached_zero_vector".
Loading pretrained parameter "encoder.encoder.W_i.weight".
Loading pretrained parameter "encoder.encoder.W_h.weight".
Loading pretrained parameter "encoder.encoder.W_o.weight".
Loading pretrained parameter "encoder.encoder.W_o.bias".
Loading pretrained parameter "ffn.1.weight".
Loading pretrained parameter "ffn.1.bias".
Loading pretrained parameter "ffn.4.weight".
Loading pretrained parameter "ffn.4.bias".
 20%|███████████████████▊                                                                               | 1/5 [02:02<08:09, 122.46s/it]Loading pretrained parameter "encoder.encoder.cached_zero_vector".
Loading pretrained parameter "encoder.encoder.W_i.weight".
Loading pretrained parameter "encoder.encoder.W_h.weight".
Loading pretrained parameter "encoder.encoder.W_o.weight".
Loading pretrained parameter "encoder.encoder.W_o.bias".
Loading pretrained parameter "ffn.1.weight".
Loading pretrained parameter "ffn.1.bias".
Loading pretrained parameter "ffn.4.weight".
Loading pretrained parameter "ffn.4.bias".
 40%|███████████████████████████████████████▌                                                           | 2/5 [03:29<05:04, 101.56s/it]Loading pretrained parameter "encoder.encoder.cached_zero_vector".
Loading pretrained parameter "encoder.encoder.W_i.weight".
Loading pretrained parameter "encoder.encoder.W_h.weight".
Loading pretrained parameter "encoder.encoder.W_o.weight".
Loading pretrained parameter "encoder.encoder.W_o.bias".
Loading pretrained parameter "ffn.1.weight".
Loading pretrained parameter "ffn.1.bias".
Loading pretrained parameter "ffn.4.weight".
Loading pretrained parameter "ffn.4.bias".
 60%|████████████████████████████████████████████████████████████                                        | 3/5 [04:44<02:58, 89.33s/it]Loading pretrained parameter "encoder.encoder.cached_zero_vector".
Loading pretrained parameter "encoder.encoder.W_i.weight".
Loading pretrained parameter "encoder.encoder.W_h.weight".
Loading pretrained parameter "encoder.encoder.W_o.weight".
Loading pretrained parameter "encoder.encoder.W_o.bias".
Loading pretrained parameter "ffn.1.weight".
Loading pretrained parameter "ffn.1.bias".
Loading pretrained parameter "ffn.4.weight".
Loading pretrained parameter "ffn.4.bias".
 80%|████████████████████████████████████████████████████████████████████████████████                    | 4/5 [05:51<01:20, 80.53s/it]Loading pretrained parameter "encoder.encoder.cached_zero_vector".
Loading pretrained parameter "encoder.encoder.W_i.weight".
Loading pretrained parameter "encoder.encoder.W_h.weight".
Loading pretrained parameter "encoder.encoder.W_o.weight".
Loading pretrained parameter "encoder.encoder.W_o.bias".
Loading pretrained parameter "ffn.1.weight".
Loading pretrained parameter "ffn.1.bias".
Loading pretrained parameter "ffn.4.weight".
Loading pretrained parameter "ffn.4.bias".
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [06:43<00:00, 80.79s/it]Saving predictions to /root/Desktop/output.csv
Elapsed time = 0:06:45
done predicting
rm: cannot remove 'TEMP_Feat': No such file or directory

```

**Comment by GemmaTuron** [comment]
Hi @Richiio 

I think removing tensorboard is breaking the pipeline. Two options: install it or copy all the chemprop code instead of pip installing it and commenting out the use of tensorboard, which indeed we don't want (like @leilayesufu did)
In addition, we should be removing the features file, so once this is solved let's make sure we do so. Maybe you need to specify the path ?

**Comment by Richiio** [comment]
Which would be preferred @GemmaTuron. I am currently pip installing chemprop. Hence, I would have to install chemprop if that would be preferred or I could also refactor and copy chemprop and comment out tensorboard instead of installing it

**Comment by GemmaTuron** [comment]
I am not sure what would be best actually... let me ping here @miquelduranfrigola let's see what is his input!

**Comment by miquelduranfrigola** [comment]
Hi,

* About the features file, we definitely have to remove it once calculations are done. This can be done in the `run.sh` file as you already do - so perfect solution already. However, I am confused with the `rm: cannot remove 'TEMP_Feat': No such file or directory` you get, @Richiio . Your `run.sh` should read `rm -r $1/TEMP_Feat.npz` instead of `rm -r TEMP_Feat.npz`
* About `tensorboard`, I know we don't need it so it would be nice to skip installation. If you go for this option, then indeed, the best is to copy/paste `chemprop` code and remove `tensorboard` imports. This said, I would not worry too much about it at the moment. If `pip install` works, then let's leave it like this for now.

Hope this helps.

**Comment by Richiio** [comment]
Thanks for the clarification @miquelduranfrigola. I'll make the necessary edits

**Comment by Richiio** [comment]
@GemmaTuron I decided to include the tensorboardX and keep the pip install of chemprop as it I had previously done. I updated the run.sh file based on the input provided by @miquelduranfrigola

**Pull request merged**
